### ISSUE TITLE
module 'matplotlib.cbook' has no attribute 'iterable'

### ISSUE THREAD

**Issue by NicoRomeo** [SkBlaz/py3plex#10]
Hi! 
I've been trying to use the multinet method visualize_network(style="diagonal") with python 3.8.5, matplotlib  3.3.1, networkx 2.5.

I always end up getting this error:

```
  File "C:\Anaconda3\envs\multilayer\lib\site-packages\py3plex\visualization\drawing_machinery.py", line 537, in draw_networkx_edges
    if not cb.iterable(width):

AttributeError: module 'matplotlib.cbook' has no attribute 'iterable'
```

Is this something with my build, or is this a call to a deprecated matplotlib module? style="hairball" works fine.

Thanks a bunch!

**Comment by SkBlaz** [comment]
Hello @NicoRomeo , thanks for pointing this out. 
It seems there exists a workaround related to matplotlib ->
https://stackoverflow.com/questions/63198347/attributeerror-module-matplotlib-cbook-has-no-attribute-iterable
does that solve it?

However, I'll have a look whether I can rewrite this part of the code to bypass the iterable as such, this might take a day or two, it seems it got deprecated in the newer versions and breaks backwards compatibility.

**Comment by SkBlaz** [comment]
Hey, I've overcome this checking with vanilla python, can you check v0.77 (just pushed) if it works fine now?
Thanks

**Comment by SkBlaz** [comment]
Hey, I'm closing this issue, as the new version 0.9 does not have the bug anymore.
