### ISSUE TITLE
Removing a node from a multilayer object

### ISSUE THREAD

**Issue by Loulz** [SkBlaz/py3plex#11]
Hello,

I am beginning with the use of Python and Py3plex for modeling multilayer networks.
I don't know if it is really the appropriate place to ask my question but could you please let me know how to remove a specific node (and all the edges associated to it) from a multilayer object  ? I didn't found the trick in the documentation.

Thanks a lot for your help and this library !

**Comment by SkBlaz** [comment]
Hello @Loulz !

Did you mean something like: https://github.com/SkBlaz/py3plex/blob/e94e205f55c229f321b233c25b0ebf4c0606ba14/examples/example_manipulation.py#L93 ?

The ./examples folder contains lots of very useful material, I'll add that to the docs in the next version though.

**Comment by SkBlaz** [comment]
This issue was a great excuse to rewrite also the dict-based removal, which is now also available btw (newest pip version of py3plex):
https://github.com/SkBlaz/py3plex/blob/bb3cc74b3c350e19ea62b45ccf68a9b7ccf14a10/examples/example_manipulation.py#L96

**Comment by SkBlaz** [comment]
closing this one - this should be clear now
