### ISSUE TITLE
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'

### ISSUE THREAD

**Issue by MrAliProgrammer** [SkBlaz/py3plex#12]
Hello good time
Thank you for providing this useful library.
To display the graph of multilayer networks with the following code snippet, we encounter an error below it and the cause is unknown. Help if you wish. thank you

code : 
mln.visualize_network(style="hairball")
plt.show()

error:
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'

**Comment by SkBlaz** [comment]
Hello, could you provide a full example so I can replicate?

**Comment by ali1400hastam** [comment]
from py3plex.visualization.multilayer import *
from py3plex.visualization.colors import all_color_names,colors_default
from py3plex.core import multinet

multilayer_network = multinet.multi_layer_network().load_network("../datasets/CSArhous.edges",directed=False, input_type="multiplexedge")
multilayer_network.basic_stats() 

 multilayer_network.visualize_network(style="hairball")
 plt.show()

**Comment by CS-ABD** [comment]
from py3plex.core import multinet
import matplotlib as plt
from py3plex.visualization.multilayer import *
from py3plex.visualization.colors import all_color_names,colors_default

mln = multinet.multi_layer_network().load_network("/home/user/Desktop/EUAir_Multiplex_Transport/EUAir_Multiplex_Transport/Dataset/EUAirTransportation_multiplex.edges",directed=False, input_type="multiedgelist")
mln.visualize_network(style="hairball")
plt.show()

**Comment by SkBlaz** [comment]
Not sure what this network is, tried with one of the examples at the repo ->

```
from py3plex.core import multinet
import matplotlib as plt
from py3plex.visualization.multilayer import *
from py3plex.visualization.colors import all_color_names,colors_default

mln = multinet.multi_layer_network().load_network("../datasets/test13.edges",directed=False, input_type="multiedgelist")
mln.visualize_network(style="hairball")
plt.show()
```

Seems to work ok

![image](https://user-images.githubusercontent.com/10035780/162366585-014a8c88-dbed-4832-90bb-66aa6aefc6ea.png)


Could you make sure that the file is in OK format (in `./datasets` there are many examples)?

**Comment by CS-ABD** [comment]
How to make sure the problem is the format; Can you help?
Or could there be another reason?

**Comment by CS-ABD** [comment]
Apparently your output is not "EUAirTransportation_multiplex.edges" data related?
Of course, I tried for other datasets, but no similar error was observed and the output showed the same as your output.
Could the data structure of some datasets have a problem?

**Comment by SkBlaz** [comment]
Could you check if you can make a
minimal example that replicates this behavior?

Recheck the dataset, theremight be some odd lines

**Comment by CS-ABD** [comment]
from py3plex.core import multinet
import matplotlib as plt
from py3plex.visualization.multilayer import *
from py3plex.visualization.colors import all_color_names,colors_default

mln = multinet.multi_layer_network().load_network("../Dataset/CS-Aarhus_multiplex.edges",directed=False,
input_type="multiedgelist")
mln.basic_stats()

Output: 
Computing core stats of the network 

MultiGraph with 235 nodes and 620 edges
Number of unique node IDs: 80
====================================================================
mln.visualize_network(style="hairball")
plt.show()

Output:
-------------------- 
 Network splitting in progress 
 --------------------
Beginning parsing..
module 'scipy.sparse' has no attribute 'coo_array'
Using standard layout algorithm, fa2 not present on the system.

![image](https://user-images.githubusercontent.com/97406919/162421155-e11f160a-e5ba-4935-a613-d2a46d38f880.JPG)

**Comment by SkBlaz** [comment]
Which scipy version are you using?

**Comment by CS-ABD** [comment]
hello,
version is 1.7.3

**Comment by CS-ABD** [comment]
Courage is another problem, of course I know I'm bothering you and I'm sorry about that.

I use this library to identify communities and I have trouble using Infomap

Also, when adding and reading the dataset, it gives the wrong number of nodes (for example, it shows 200 nodes instead of 61).

What do you think might be the problem?

**Comment by CS-ABD** [comment]
I think the problem is with datasets, I mean the format of datasets
Because the datasets I created are all of them ".edge" , but the recommended format is your library ".edgelist".

**Comment by SkBlaz** [comment]
Yes, please re-check the format, there must be something off during parsing

**Comment by CS-ABD** [comment]
Yes, I will check again
Thank you for all your tips
Good luck.

**Comment by SkBlaz** [comment]
Closing this, as it does not appear to be relevant to scipy version anymore

**Comment by SkBlaz** [comment]
Could you update your scipy?
