### ISSUE TITLE
SyntaxError: in print message in class multi_layer_network, function split_to_layers

### ISSUE THREAD

**Issue by TanjaEraerds** [SkBlaz/py3plex#13]
In function split_to_layers in class multi_layer_network in file multinet.py is a syntax error in a print statement.
Current line 569 should be be print(self.separate_layers) instead of print(separate_layers)

**Comment by SkBlaz** [comment]
Thanks! Could you open a PR please?

**Comment by SkBlaz** [comment]
Hello, possible, could you open a PR with a fix perhaps?

**Comment by SkBlaz** [comment]
Fixed this with the latest master (0.95a)
