### ISSUE TITLE
Matplolib Axes Error 

### ISSUE THREAD

**Issue by jsnagai** [SkBlaz/py3plex#17]
Hi All,

First of all, thank you for this awesome library, the concept and the library is really really nice.

I'm trying to test the library with a dataset but got some troubles related to Matplotlib and the code, Does anyone have a clue about how this issue could be handled or any workaround?

Best Regards

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [47], line 2
      1 A.basic_stats()
----> 2 A.visualize_network(style="diagonal")

--> 201         drawing_machinery.draw(network,
    202                                positions,
    203                                node_color=facecolor_list[color],
    204                                with_labels=node_labels,
    205                                edge_size=edge_size,
    206                                node_size=node_sizes,
    207                                arrowsize=arrowsize,
    208                                ax=axis,
    209                                font_size=node_font_size)
    210         color += 1
    212     if display == True:

File ~/.local/lib/python3.10/site-packages/py3plex/visualization/drawing_machinery.py:88, in draw(G, pos, ax, **kwds)
     86 cf.set_facecolor('w')
     87 if ax is None:
---> 88     if cf._axstack() is None:
     89         ax = cf.add_axes((0, 0, 1, 1))
     90     else:

TypeError: '_AxesStack' object is not callable

matplotlib version 3.6.0

**Comment by SkBlaz** [comment]
We merged this, lmk if we can close?

**Comment by SkBlaz** [comment]
`mpl` was pinned alongside networkx, released py3plex==0.95 where visualizations examples seems to work fine (`example_multilayer_visualization.py`) - let's re-open the issue for the new version if it persists
