### ISSUE TITLE
_AxesStack' object is not callable

### ISSUE THREAD

**Issue by kazim01011** [SkBlaz/py3plex#21]
TypeError: '_AxesStack' object is not callable

I am trying to just run https://github.com/SkBlaz/py3plex/blob/master/examples/example_multilayer_visualization.py this example and gives me the above error. Can anybody help me please

**Comment by SkBlaz** [comment]
@kazim01011 we just released a new version (0.95) that has mpl + nx libraries pinned - this seemed to have been the issue (examples seem to work fine now)

**Comment by SkBlaz** [comment]
Please re-open the issue if it persists in the new version
