### ISSUE TITLE
Community partition error

### ISSUE THREAD

**Issue by ashuein** [SkBlaz/Py3plex#5]
I am trying to run this simple code

`from py3plex.core import multinet`
`from py3plex.core import random_generators`
`from py3plex.algorithms.community_detection import community_louvain as cwl`

Initiate an instance of a random graph
`ER_multilayer = random_generators.random_multilayer_ER(500,8,0.05,directed=False)`

Finding best partition

`partition = cwl.best_partition(ER_multilayer)`

**It gives the following error:**

  `File "<ipython-input-136-79ea27059665>", line 1, in <module>`
   `partition = cwl.best_partition(ER_multilayer)`

  `File "/usr/local/lib/python3.6/dist-packages/py3plex/algorithms/community_detection/community_louvain.py", line 292, in best_partition randomize)`

  `File "/usr/local/lib/python3.6/dist-packages/py3plex/algorithms/community_detection/community_louvain.py", line 358, in generate_dendrogram`
   ` if graph.is_directed():`

`AttributeError: 'multi_layer_network' object has no attribute 'is_directed'`

**Also, importing the community wrapper also gives the following error**

`from py3plex.algorithms.community_detection import community_wrapper as cw`

`Traceback (most recent call last):`

 ` File "<ipython-input-137-ffcfd3de8e39>", line 1, in <module>`
    `from py3plex.algorithms.community_detection import community_wrapper as cw`

  `File "/usr/local/lib/python3.6/dist-packages/py3plex/algorithms/community_detection/community_wrapper.py", line 5, in <module>
    from .NoRC import *`

 ` File "/usr/local/lib/python3.6/dist-packages/py3plex/algorithms/community_detection/NoRC.py", line 16, in <module>`
   ` import community`

`ModuleNotFoundError: No module named 'community'`

**Comment by SkBlaz** [comment]
Hello Ashuein. I've added an example demonstrating how to perform Louvain on top of ER graphs. There is a reason for another abstraction layer between the algorithms and the API. Please, re install with the newest commit for this to work:

https://github.com/SkBlaz/Py3plex/blob/master/examples/example_community_detection.py (lines 9-13)

**Comment by ashuein** [comment]
Your new commit works with the random multilayer function, but not with the ../datasets/simple_multiplex.edgelist

I tried with the original data file, then I modified to include all nodes in all layers and then I tried by removing any string identification in the edge list file

The new edgelist looks like this:

`1 1 2 1`
`1 1 3 1`
`1 1 4 1`
`2 1 2 1`
`2 1 3 1`
`2 1 4 1`
`3 1 2 1`
`3 1 3 1`
`3 1 4 1`


The layer file looks like this:

`LayerID LayerName`
`1 hub`
`2 transport`
`3 utility`

But on running the Louvian community code on all possible files as mentioned above

`comNet = multinet.multi_layer_network().load_network('../Py3plex_master/datasets/simple_multiplex.edgelist',directed=False,input_type='multiplex_edges')`
`comNet.basic_stats()`
`comNet.load_layer_name_mapping('../Py3plex_master/datasets/simple_multiplex.txt')`
`mat = comNet.get_supra_adjacency_matrix()`

`part = cw.louvain_communities(comNet)`


I get the following error:

Traceback (most recent call last):

  File "<ipython-input-16-7e5ae46da9cc>", line 1, in <module>
    part = cw.louvain_communities(comNet)

  File "/usr/local/lib/python3.6/dist-packages/py3plex-0.59-py3.6.egg/py3plex/algorithms/community_detection/community_wrapper.py", line 94, in louvain_communities
    partition = best_partition(network)

  File "/usr/local/lib/python3.6/dist-packages/py3plex-0.59-py3.6.egg/py3plex/algorithms/community_detection/community_louvain.py", line 292, in best_partition
    randomize)

  File "/usr/local/lib/python3.6/dist-packages/py3plex-0.59-py3.6.egg/py3plex/algorithms/community_detection/community_louvain.py", line 371, in generate_dendrogram
    status.init(current_graph, weight, part_init)

  File "/usr/local/lib/python3.6/dist-packages/py3plex-0.59-py3.6.egg/py3plex/algorithms/community_detection/community_louvain.py", line 57, in init
    self.total_weight = graph.size(weight=weight)

  File "/usr/local/lib/python3.6/dist-packages/networkx/classes/graph.py", line 1785, in size
    s = sum(d for v, d in self.degree(weight=weight))

  File "/usr/local/lib/python3.6/dist-packages/networkx/classes/graph.py", line 1785, in <genexpr>
    s = sum(d for v, d in self.degree(weight=weight))

  File "/usr/local/lib/python3.6/dist-packages/networkx/classes/reportviews.py", line 529, in __iter__
    deg = sum(d.get(weight, 1) for key_dict in nbrs.values()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by SkBlaz** [comment]
I've corrected this now. It was indeed a bug. Check the
example_community_detection.py sample code.

**Comment by ashuein** [comment]
it works now.

**Comment by ashuein** [comment]
How do you keep track of node id and names? seems like, after community partitioning, the node labels are not the original ones. So how do I know the identity of the nodes? In the package, there are a sample multiplex datasets in the ../Multilayer_datasets folder. There I see that a separate file with node name and index has been mentioned. I did the same for my data but seems like it wasn't used and hence the final partition doesn't keep track of the original node name and the corresponding node ids

**Comment by SkBlaz** [comment]
The function, which adds the couplings was already implemented (forgot
about that one).

Please, check examples/example_supra_adjacency.py to see how this works.
Basically you need to specify multiplex network type during object
initialization. Is this what you meant?

**Comment by ashuein** [comment]
I am closing this issue as I didn't have any problems with this further
