### ISSUE TITLE
Some issues in multilayer

### ISSUE THREAD

**Issue by Snaicol** [SkBlaz/Py3plex#7]
Hi, i'm sure you'll hate me sooner or later. But i have still some problems during plot. I have no time right now to find the problem so i'm just "reporting" (for now).

So, i'm attaching the file edgeList.txt i'm using
[edgeList.txt](https://github.com/SkBlaz/Py3plex/files/3370128/edgeList.txt)

Code is always the same as before. But this is the plot
![Immagine](https://user-images.githubusercontent.com/9090815/60841305-cbbe6480-a1d1-11e9-9308-b10bb1f1bd90.png)

Like before i'm pretty sure it is wrong.
I'm attaching the log too. 
[log.txt](https://github.com/SkBlaz/Py3plex/files/3370167/log.txt)

Can you have a look? =)

**Comment by SkBlaz** [comment]
Thanks for the example, on it!

**Comment by SkBlaz** [comment]
Hey @Snaicol , this was indeed an issue in the parser (all isolated nodes). I've fixed this + added your graph to the following example files (if you do not mind):

![exampleX](https://user-images.githubusercontent.com/10035780/61173118-fff9a280-a58e-11e9-8d14-0d05197819ff.png)
https://github.com/SkBlaz/Py3plex/blob/master/examples/example_multilayer_visualization.py (first example)

https://github.com/SkBlaz/Py3plex/blob/master/examples/example_IO.py (just parser example) 

If this is still something you find wrong, please, do not hesitate to write!
