### ISSUE TITLE
error in "./core/multinet.py"

### ISSUE THREAD

**Issue by chaoshengt** [SkBlaz/py3plex#9]
when i run the code ,it appeared:

multinet.py:791: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.

How to fix it?

**Comment by SkBlaz** [comment]
Interesting, thanks for pointing this out! Could you provide a minimal example so I can reproduce this?

Thanks!

**Comment by SkBlaz** [comment]
I've refactored this part now:
https://github.com/SkBlaz/py3plex/blob/master/examples/example_numeric_encoding.py
hope this helps.

**Comment by chaoshengt** [comment]
> I've refactored this part now:
> https://github.com/SkBlaz/py3plex/blob/master/examples/example_numeric_encoding.py
> hope this helps.

Thank you  :)
